### ISSUE TITLE
Add cmake support

### ISSUE THREAD

**Issue by KestrelAdrian** [KestrelRadarSensors/dockingpanes#3]
Support for the cmake build system is pretty much a requirement these days, it's far superior to qmake and will be the default build system in future releases of Qt.

**Comment by lmsoria** [comment]
Hi Adrian,
I hope you're doing good. You may want to take a look at [this branch](https://github.com/lmsoria/dockingpanes/tree/lmsoria/add-cmake-support). I've added CMake support. Since I'm not an expert on CMake, some friends of mine helped me on the process.
We added an option to build the library both as an static library and as a shared lib as well.
Other option allows the user to build the examples (simple , currently)
I've tested successfully the branch on Ubuntu 16.04 and Qt 5.5. A friend tested it successfully on Windows 10 and Qt 5.12. He even setup [actions for github](https://github.com/cocus/dockingpanes/actions/runs/261590120) in order to do CI builds for PRs against this repo.

As you will notice, the only header exposed is `DockingPaneManager.h`. Is this approach right? If not, what headers do you consider must be added to the `PUBLIC_HEADER` variable?

Should you have any suggestion or comment, please let me know! Thanks in advance, and sorry If I'm making you feel overwhelmed for the amount of Pull Requests.

**Comment by KestrelAdrian** [comment]
the patches provided by @lmsoria add CMake support to the library, closing issue.

Many thanks.
